harness-mongo:
  uri: mongodb://localhost:30003/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

events-mongo:
  uri: mongodb://localhost:27017/events
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

timescaledb:
  timescaledbUrl: "jdbc:postgresql://34.83.25.129:5432/harnessdev"
  timescaledbUsername: "harnessappdev"
  timescaledbPassword: "harnessappdev"
  connectTimeout: 10
  socketTimeout: 30
  logUnclosedConnections: false
  loggerLevel: OFF