logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

server:
  applicationConnectors:
    - type: http
      port: 12001
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 12002
  requestLog:
    appenders: []
  maxThreads: 1024

mongo:
  uri: mongodb://localhost:27017/pms-harness
  connectTimeout: ${MONGO_CONNECT_TIMEOUT:-30000}
  serverSelectionTimeout: ${MONGO_SERVER_SELECTION_TIMEOUT:-90000}
  maxConnectionIdleTime: ${MAX_CONNECTION_IDLE_TIME:-600000}
  connectionsPerHost: ${MONGO_CONNECTIONS_PER_HOST:-300}
  indexManagerMode: ${MONGO_INDEX_MANAGER_MODE:-AUTO}
  transactionsEnabled: false
  aliasDBName:  pms-harness

grpcServerConfig:
  connectors:
    - port: 12011
      secure: true
      keyFilePath: 800-pipeline-service/key.pem
      certFilePath: 800-pipeline-service/cert.pem
    - port: 12012

grpcClientConfigs:
  cd:
    target: ${NG_MANAGER_TARGET:-localhost:12101}
    authority: ${NG_MANAGER_AUTHORITY:-localhost}
  cvng:
    target: ${CVNG_MANAGER_TARGET:-localhost:12401}
    authority: ${CVNG_MANAGER_AUTHORITY:-localhost}
  ci:
    target: ${CI_MANAGER_TARGET:-localhost:12301}
    authority: ${CI_MANAGER_AUTHORITY:-localhost}

yamlSchemaClientConfig:
  yamlSchemaHttpClientMap:
    ci:
      serviceHttpClientConfig:
        baseUrl: ${CI_MANAGER_BASE_URL:-http://localhost:4457/}
        connectTimeOutSeconds: 15
        readTimeOutSeconds: 15
      secret: ${CI_MANAGER_SERVICE_SECRET:-IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM}
    cd:
      serviceHttpClientConfig:
        baseUrl: ${NG_MANAGER_BASE_URL:-http://localhost:7457/}
        connectTimeOutSeconds: 15
        readTimeOutSeconds: 15
      secret: ${NG_MANAGER_SERVICE_SECRET:-IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM}



managerTarget: ${MANAGER_TARGET:-localhost:9880}
managerAuthority: ${MANAGER_AUTHORITY:-localhost}

eventsFramework:
  redis:
    sentinel: ${EVENTS_FRAMEWORK_USE_SENTINEL:-false}
    masterName: ${EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME:-"test"}
    redisUrl: ${EVENTS_FRAMEWORK_REDIS_URL:-redis://localhost:6379}
    sentinelUrls:
      - "redis://redis1:26379"
      - "redis://redis2:26379"
      - "redis://redis3:26379"
    envNamespace: ${EVENTS_FRAMEWORK_ENV_NAMESPACE:-""}
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true
    userName: ${EVENTS_FRAMEWORK_REDIS_USERNAME:-""}
    password: ${EVENTS_FRAMEWORK_REDIS_PASSWORD:-""}
    sslConfig:
      enabled: ${EVENTS_FRAMEWORK_REDIS_SSL_ENABLED:-false}
      CATrustStorePath: ${EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PATH:-false}
      CATrustStorePassword: ${EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PASSWORD:-""}

managerClientConfig:
  baseUrl: ${MANAGER_BASE_URL:-http://localhost:3457/api/}
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15
managerServiceSecret: ${MANAGER_SERVICE_SECRET:-IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM}

notificationClient:
  messageBroker:
    type: MONGO
    uri: mongodb://localhost:27017/notification
    connectTimeout: 30000
    serverSelectionTimeout: 90000
    maxConnectionIdleTime: 600000
    connectionsPerHost: 300
  httpClient:
    baseUrl: ${NOTIFICATION_BASE_URL:-http://localhost:9005/api/}
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  secrets:
    notificationClientSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

ngManagerServiceHttpClientConfig:
  baseUrl: ${NG_MANAGER_BASE_URL:-http://localhost:7457/}
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15
ngManagerServiceSecret: ${NG_MANAGER_SERVICE_SECRET:-IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM}
jwtAuthSecret: ${JWT_AUTH_SECRET:-dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq}
jwtIdentityServiceSecret: ${JWT_IDENTITY_SERVICE_SECRET:-HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=}

allowedOrigins:
  - "*"

accessControlClient:
  enableAccessControl: false
  accessControlServiceConfig:
    baseUrl: http://localhost:9006/api/
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  accessControlServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

pipelineServiceBaseUrl: ${PIPELINE_SERVICE_BASE_URL:-https://localhost:8181/#}
pmsApiBaseUrl: http://localhost:12001/api/

logStreamingServiceConfig:
  baseUrl: http://localhost:8079
  serviceToken: token

iteratorsConfig:
  approvalInstanceIteratorConfig:
    enabled: true
    targetIntervalInSeconds: 60

orchestrationStepConfig:
  ffServerBaseUrl: http://127.0.0.1:3000/api/1.0

shouldDeployWithGitSync: false

gitSdkConfiguration:
  gitSdkGrpcServerConfig:
    connectors:
      - port: 14001
        secure: true
        keyFilePath: key.pem
        certFilePath: cert.pem
      - port: 14002
  gitManagerGrpcClientConfig:
    target: localhost:13001
    authority: localhost
  scmConnectionConfig:
    url: localhost:8091

enableDashboardTimescale: false

enableAuth: ${AUTH_ENABLED:-false}

timescaledb:
  timescaledbUrl: "jdbc:postgresql://34.83.25.129:5432/harnessdev"
  timescaledbUsername: "harnessappdev"
  timescaledbPassword: "harnessappdev"
  connectTimeout: 10
  socketTimeout: 30
  logUnclosedConnections: false
  loggerLevel: OFF